################################# 通用参数 #################################
general:
  lambda_      : 0.01   # 光流法正则化参数(速度场平滑项参数)
  eps          : 0.0001     # 判断速度是否为0的误差
  time_steps   : 98 # 时间步数
  processes_num: 32 # 进程池大小

################################# 模拟数据参数 ################################# 
simulated_data:
  e_path                      : './simulated_data/simulated_two_source/e.csv'   # 基底向量保存路径
  V_k_path                    : './simulated_data/simulated_two_source/V_k.csv' # 速度场保存路径
  surface_path                : './simulated_data/simulated_two_source/simulated_surface.ply' # 三角剖分的表面文件路径
  potentials_path             : './simulated_data/simulated_two_source/simulated_potentials.csv' # 电势数据文件路径
  potentials_path_2           : './simulated_data/simulated_two_source/simulated_potentials_2.csv' # 电势数据文件2路径
  threshold                   : 10.0  # 判断检测到的临界点是否与真实临界点对应的阈值
  singularity_points_path     : './simulated_data/simulated_two_source/singularity_points.pkl' # 检测到的临界点保存路径
  true_singularity_points_path: './simulated_data/true_singularity_points.pkl' # 真实临界点保存路径
  # processed_surface_path      : './simulated_data/simulated_two_source/simulated_processed_surface_arrays.npz' # 几何相关数信息保存路径


################################# 真实数据参数 #################################
sub_01:
  surface_path            : '/fred/oz284/mc/data/CCEP-sub-01/sub-ccepAgeUMCU01_reconstructed_surface.ply'  # 三角剖分的表面文件路径
  potentials_path         : '/fred/oz284/mc/results/CCEP-sub-01/optical_flow/sub_01-PT21-PT22-ave-interpolation_data.csv'  # 电势数据文件路径
  e_path                  : "/fred/oz284/mc/results/CCEP-sub-01/optical_flow/sub-p01_e.csv"  # 基底向量保存路径
  V_k_path                : "/fred/oz284/mc/results/CCEP-sub-01/optical_flow/sub-p01_V_k.csv"  # 速度场保存路径
  processed_surface_path  : '/fred/oz284/mc/results/CCEP-sub-01/optical_flow/sub-p01_processed_surface_arrays.npz'  # 几何相关数信息保存路径
  singularity_points_path : '/fred/oz284/mc/results/CCEP-sub-01/optical_flow/sub-p01_singularity_points.pkl'  # 检测到的临界点保存路径
  velocity_fields_gif_path: '/fred/oz284/mc/results/CCEP-sub-01/optical_flow/velocity_fields.gif'  # 光流场绘制保存路径


sub_08:
  epochs_save_path                      : "results/sub-p08/preprocessed_data/sub-p08_ses-nyuecog01_task-prf_acq-clinical_run-01-epo.fif"
  surface_path                          : 'results/sub-p08/preprocessed_data/sub-p08_reconstructed_surface.ply'  # 三角剖分的表面文件路径
  potentials_path                       : 'results/sub-p08/preprocessed_data/trials_potentials/sub-p08_ses-nyuecog01_task-prf_acq-clinical_run-01_VERTICAL-L-R-1_01_potentials.csv'  # 电势数据文件路径
  e_path                                : "results/sub-p08/optical_flow/sub-p08_ses-nyuecog01_task-prf_acq-clinical_run-01_VERTICAL-L-R-1_01/e.csv"  # 基底向量保存路径
  V_k_path                              : "results/sub-p08/optical_flow/sub-p08_ses-nyuecog01_task-prf_acq-clinical_run-01_VERTICAL-L-R-1_01/V_k.csv"  # 速度场保存路径
  # processed_surface_path                : 'results/sub-p08/optical_flow/sub-p08_ses-nyuecog01_task-prf_acq-clinical_run-01_VERTICAL-L-R-1_01/sub-p01_processed_surface_arrays.npz'  # 几何相关数信息保存路径
  singularity_points_path               : 'results/sub-p08/optical_flow/sub-p08_ses-nyuecog01_task-prf_acq-clinical_run-01_VERTICAL-L-R-1_01/singularity_points.pkl'  # 检测到的临界点保存路径
  singularity_points_classification_path: 'results/sub-p08/optical_flow/sub-p08_ses-nyuecog01_task-prf_acq-clinical_run-01_VERTICAL-L-R-1_01/singularity_points_classification.pkl'
  velocity_fields_gif_path              : 'results/sub-p08/optical_flow/sub-p08_ses-nyuecog01_task-prf_acq-clinical_run-01_VERTICAL-L-R-1_01/velocity_fields.gif'  # 光流场绘制保存路径


