################################# 通用参数 #################################
general:
  lambda_      : 0.01   # 光流法正则化参数(速度场平滑项参数)
  eps          : 0.0001     # 判断速度是否为0的误差
  time_steps   : 308 # 时间步数
  processes_num: 16 # 进程池大小

################################# 模拟数据参数 ################################# 
# simulated_data:
#   e_path                      : './simulated_data/simulated_two_source/e.csv'   # 基底向量保存路径
#   V_k_path                    : './simulated_data/simulated_two_source/V_k.csv' # 速度场保存路径
#   surface_path                : './simulated_data/simulated_two_source/simulated_surface.ply' # 三角剖分的表面文件路径
#   potentials_path             : './simulated_data/simulated_two_source/simulated_potentials.csv' # 电势数据文件路径
#   potentials_path_2           : './simulated_data/simulated_two_source/simulated_potentials_2.csv' # 电势数据文件2路径
#   threshold                   : 10.0  # 判断检测到的临界点是否与真实临界点对应的阈值
#   singularity_points_path     : './simulated_data/simulated_two_source/singularity_points.pkl' # 检测到的临界点保存路径
#   true_singularity_points_path: './simulated_data/true_singularity_points.pkl' # 真实临界点保存路径
#   processed_surface_path      : './simulated_data/simulated_two_source/simulated_processed_surface_arrays.npz' # 几何相关数信息保存路径



################################# 真实数据参数 #################################
sub_01:
  surface_path            : './reconstructed_surface/sub-p01_reconstructed_surface.ply'  # 三角剖分的表面文件路径
  potentials_path         : './interpolation_data/sub-p01_ses-umcuiemu01_task-prf_acq-clinical_run-01_ieeg.csv'  # 电势数据文件路径
  e_path                  : "./results/sub-01/sub-p01_e.csv"  # 基底向量保存路径
  V_k_path                : "./results/sub-01/sub-p01_V_k.csv"  # 速度场保存路径
  processed_surface_path  : './results/sub-01/sub-p01_processed_surface_arrays.npz'  # 几何相关数信息保存路径
  singularity_points_path : './results/sub-01/sub-p01_singularity_points.pkl'  # 检测到的临界点保存路径
  velocity_fields_gif_path: './results/sub-01/velocity_fields.gif'  # 光流场绘制保存路径


# root: E:/毕设数据/ds004194_Visual_ECoG_dataset
# save_root: E:/毕设数据/wangxi/processed_open_data
# ecog_names_path: ./derivatives/ecog_names.csv
# reconstructed_surface_path: ./reconstructed_surface

